const content = {
  english: {
    title: 'In Loving Memory',
    biography: 'Biography',
    survivedBy: 'Survived By',
    tribute: 'Tribute',
    funeral: 'Funeral Details',
    photos: 'Photos',
    condolences: 'Condolences',
    submitCondolence: 'Submit Condolence',
    name: 'Name',
    email: 'Email',
    message: 'Message',
    submit: 'Submit',
    venue: 'Venue',
    address: 'Address',
    dateTime: 'Date & Time',
    directions: 'Get Directions',
    liveStream: 'Live Stream',
    language: 'Language',
    recentMessages: 'Recent Messages',
    serviceInfo: 'Service Information',
    location: 'Location',
    additionalInfo: 'Additional Information',
    joinVirtually: 'Join us virtually for the service',
    celebrateLife: 'Please join us as we celebrate the life of',
    honorMemory: 'and honor their memory.',
    contactFamily: 'For any questions, please contact the family.',
    galleryComingSoon: 'Photo Gallery Coming Soon',
    memoriesWillBeShared: 'Beautiful memories and photos will be shared here.',
    returnToMemorial: 'Return to Memorial',
    familyPhotoGallery: 'Family Photo Gallery',
    thankYou: 'Thank you for your condolence message. It will be reviewed and posted shortly.',
    withLove: 'With love and remembrance',
    inLovingMemoryOf: 'In loving memory of'
  },
  malayalam: {
    title: 'സ്നേഹപൂർവ്വം ഓർത്ത്',
    biography: 'ജീവചരിത്രം',
    survivedBy: 'അനുജീവിച്ചവർ',
    tribute: 'ആദരാഞ്ജലി',
    funeral: 'ശവസംസ്കാര വിശേഷങ്ങൾ',
    photos: 'ഫോട്ടോകൾ',
    condolences: 'അനുശോചന സന്ദേശങ്ങൾ',
    submitCondolence: 'അനുശോചനം അയയ്ക്കുക',
    name: 'പേര്',
    email: 'ഇമെയിൽ',
    message: 'സന്ദേശം',
    submit: 'അയയ്ക്കുക',
    venue: 'സ്ഥലം',
    address: 'വിലാസം',
    dateTime: 'തീയതിയും സമയും',
    directions: 'വഴികാട്ടി',
    liveStream: 'തത്സമയ പ്രക്ഷേപണം',
    language: 'ഭാഷ',
    recentMessages: 'സമീപകാല സന്ദേശങ്ങൾ',
    serviceInfo: 'സേവന വിവരങ്ങൾ',
    location: 'സ്ഥാനം',
    additionalInfo: 'അധിക വിവരങ്ങൾ',
    joinVirtually: 'സേവനത്തിനായി വെർച്ച്വലായി ചേരുക',
    celebrateLife: 'ജീവിതം ആഘോഷിക്കാൻ ഞങ്ങളോടൊപ്പം ചേരുക',
    honorMemory: 'അവരുടെ ഓർമ്മയെ ബഹുമാനിക്കുക.',
    contactFamily: 'എന്തെങ്കിലും ചോദ്യങ്ങൾക്ക്, ദയവായി കുടുംബത്തെ ബന്ധപ്പെടുക.',
    galleryComingSoon: 'ഫോട്ടോ ഗാലറി ഉടനെ വരുന്നു',
    memoriesWillBeShared: 'മനോഹരമായ ഓർമ്മകളും ഫോട്ടോകളും ഇവിടെ പങ്കിടും.',
    returnToMemorial: 'സ്മാരകത്തിലേക്ക് മടങ്ങുക',
    familyPhotoGallery: 'കുടുംബ ഫോട്ടോ ഗാലറി',
    thankYou: 'നിങ്ങളുടെ അനുശോചന സന്ദേശത്തിന് നന്ദി. ഇത് അവലോകനം ചെയ്ത് ഉടനെ പോസ്റ്റ് ചെയ്യും.',
    withLove: 'സ്നേഹത്തോടും ഓർമ്മയോടും കൂടി',
    inLovingMemoryOf: 'സ്നേഹപൂർവ്വം ഓർത്ത്'
  }
};

const getContent = (language = 'english') => {
  return content[language] || content.english;
};

module.exports = { getContent };
